name: Pull and rebase upstream

on:
  workflow_dispatch:
  schedule:
    - cron:  '5 9 */2 * *'

jobs:
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PUSH_TOKEN }}

      - run: |
          git config user.email "myzhang1029_bot@outlook.com"
          git config user.name "Zhang Maiyun (Bot)"

      - name: Fetch upstream
        run: |
          git remote add upstream https://github.com/audacity/audacity.git
          git fetch upstream
  
      - name: Rebase onto upstream/master
        run: git rebase upstream/master
          
      - name: Push to audacity-applesilicon
        run: |
          git push --force-with-lease
          git push --all
          git push --tags
